name: flutter_mlkit_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  provider: ^4.0.3
  firebase_ml_vision: ^0.9.3+5
  image_picker: ^0.6.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_automation: any

flutter:  
  uses-material-design: true
